### ISSUE TITLE
Query builder does not keep multiple uses of "long_list" with "=" operator

### ISSUE THREAD

**Issue by ccaio** [genomehubs/goat-ui#1]
Query builder does not keep previous terms when using the same target_lists values and the operator "=" . For example, searching for <long_list> <= > is only allowed once in the query builder.
Using both "=" and "==" in the query builder when specifying two "long_list" values does not erase the query whereas using only "=" erases one of the values.

**Comment by rjchallis** [comment]
This has been fixed by treating conditions as lists in genomehubs ui/api
